GET http://localhost:8080/info
# GET http://localhost:8080/sample-0.0.1-SNAPSHOT/info
###

# GET http://localhost:8080/config
GET http://localhost:8080/sample-0.0.1-SNAPSHOT/config

###

# GET http://localhost:8080/search?query=thorntail
GET http://localhost:8080/sample-0.0.1-SNAPSHOT/search?query=thorntail

###